name: Build and Commit Dist

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and push changes
permissions:
  contents: write

jobs:
  build_and_commit: # Renamed job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Specify pnpm version if needed, or remove for latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use Node.js version 20
          cache: 'pnpm' # Enable caching for pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build
        env:
          CONTACT_FORMSUBMIT_DEFAULT_ID: ${{ secrets.CONTACT_FORMSUBMIT_DEFAULT_ID }}
          CONTACT_FORMSUBMIT_QUOTE_ID: ${{ secrets.CONTACT_FORMSUBMIT_QUOTE_ID }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist
          # Check if there are staged changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: build site [skip ci]"
            git push
          fi